=== perryflynn/minimon/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "https://files.serverless.industries/schemas/minimon.json",
    "title": "JSON schema for minimon.sh",
    "type": "object",
    "properties": {
        "checks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "type": { "type": "string", "enum": [ "icmp", "http", "tcp", "script" ] },
                    "proto": { "type": "string", "enum": [ "0", "4", "6" ] },
                    "url": { "type": "string" },
                    "alias": { "type": "string" }
                },
                "required":[ "type", "url" ]
            }
        },
        "invalid-tls": {
            "type": "boolean"
        },
        "unsafe-tls": {
            "type": "boolean"
        },
        "interval": {
            "type": "integer",
            "minimum": 1
        },
        "parallel": {
            "type": "integer",
            "minimum": 1
        },
        "timeout": {
            "type": "integer",
            "minimum": 1
        },
        "connect-timeout": {
            "type": "integer",
            "minimum": 1
        },
        "time-spacer": {
            "type": "integer",
            "minimum": 0
        },
        "max-checks": {
            "type": "integer",
            "minimum": 1
        },
        "no-timestamps": {
            "type": "boolean"
        },
        "short-timestamps": {
            "type": "boolean"
        },
        "warnings": {
            "type": "boolean"
        },
        "errors": {
            "type": "boolean"
        },
        "verbose": {
            "type": "boolean"
        },
        "no-redirect": {
            "type": "boolean"
        }
    }
}

=== perryflynn/minimon/example_config.json
{
    "$schema": "https://files.serverless.industries/schemas/minimon.json",
    "checks": [
        { "type": "http", "url": "http://example.com", "alias": "example" },
        { "type": "icmp", "url": "8.8.8.8", "proto": "4" }
    ],
    "invalid-tls": true,
    "interval": 10,
    "parallel": 5,
    "timeout": 5,
    "connect-timeout": 2
}
